### ISSUE TITLE
Validate token on custom routes

### ISSUE THREAD

**Issue by shash7** [Tmeister/wp-api-jwt-auth#120]
I've setup custom rest endpoints and would like to make them accessible only if the bearer token is present and valid.

Is there a method exposed by the plugin via which I can validate the token?

Currently my rest route is looking like this:
```
add_action( 'rest_api_init', function () {

  register_rest_route('chats/v1', '/chat/(?P<id>\d+)', array(
    'methods' => 'GET',
    'callback' => __NAMESPACE__ . '\\get_chat',
    'args' => array(
      'id' => array(
        'validate_callback' => function($param, $request, $key) {
          return is_numeric($param);
        }
      )
    )
  ));
});

function get_chat() {
$results = $data->get_params();
$isValid = validate_token($results); // I guess the method would look something like this?
}
```

**Comment by milossh** [comment]
Bump. Any news on this one?

**Comment by Tmeister** [comment]
Well, this has nothing to do with the JWT authentication plugin.

If you are using custom endpoint you should set the permissions for that endpoints please see the [Permissions Callback](https://v2.wp-api.org/extending/adding/#permissions-callback) documentation for the REST API.

Also, the native PHP function [getallheaders](http://php.net/manual/en/function.getallheaders.php) should be handy for you, with this function you can fetch all HTTP request headers.

Best,

**Comment by shash7** [comment]
@Tmeister thanks for that. I've setup custom endpoints but how do setup a permission where the token is valid?

Would be good if this plugin can expose a standalone function to validate a token. Something like this:
```
$isValid = checkToken($token);
if($isValid) { ...
```

**Comment by virtualLast** [comment]
*bump

**Comment by cschweda** [comment]
Yes -- my question as well. Is there any way to validate the token once I've snagged the headers on the php side?

I'm using a Vue spa app on the front -- but I need some custom routes on the Wordpress side -- and I want to require a valid token before I display the routes via the API.

**Comment by pbredenberg** [comment]
For posterity (because related threads on this project make this clear as mud):

If your server is configured correctly, there is no need to manually validate the token. When this plugin is installed, and the token is valid, the **user should be automatically available** with your custom REST route.

Make sure you've followed the configuration in the readme for this project as regards `.htaccess` (if you're using Apache). There may be alternate configuration required if you're using nginx.

The first five lines of your `.htaccess` file should look like this:

```
RewriteEngine On
RewriteBase /
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
RewriteRule ^index\.php$ - [L]
```

If you've set the Authorization header and passed it along with your request, methods that return the "current user" such as `wp_get_current_user()` should be available to you and then you have all you need to verify permissions.

What @Tmeister points out is the best practice for validating permissions.

**Comment by virtualLast** [comment]
@pbredenberg Thanks my dude, I had figured it out but good to get a clear answer documented.
