### ISSUE TITLE
Incompatibility with wordpress 5.0

### ISSUE THREAD

**Issue by daniloalvess** [Tmeister/wp-api-jwt-auth#126]
I'm testing WordPress 5.0 Beta 3 and found a incompatibility with the plugin.
On editing a post, some routes return error 500:

- `wp-json/wp/v2/users/?who=authors&per_page=100&_locale=user`
- `wp-json/wp/v2/taxonomies?context=edit&_locale=user`

After debugging, I think the error is on filter `determine_current_user`. 

File: jwt-authentication-for-wp-rest-api/includes/class-jwt-auth.php on line 144

**Comment by Tmeister** [comment]
Thank you for the report.

I published a new [version (1.2.5)](https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/) to the repo, it fixes the recursion issue, but I will leave the issue open in case someone else has issues with Gutenberg.

Thanks again!

**Comment by N-Molham** [comment]
@Tmeister @daniloalvess 

I just faced this issue and here is what I found to solve it:

if the request has the authentication cookie in the header `wordpress_logged_in_*` the JWT `Bearer` header parameter will be ignored, so make sure to make all the REST Request without that cookie, to make the JWT authentication work correctly.

I spent like an hour to figure it out after the last update for the JWT plugin

https://www.dropbox.com/s/tdcnexut9fbknnf/phpstorm64_2018-11-29_18-49-05.png?dl=0

The `determine_current_user` filter which parses the request header looking for the JWT token. As you can see in the screenshot, because of Gutenberg fix, it ignores it. I don't this it's the author mistake by the way

**Comment by lmartins** [comment]
I'm having an issue that appears to be related to this.
The request to get a new token runs successfully, but everything after that returns a 403 with the message `Signature verification failed`.

I'm sending the token I get from the initial request, and I've already disabled cookies on my http client.

Any tips of what else might be going wrong?

**Comment by andrzejpiotrowski** [comment]
@daniloalvess @N-Molham would you look at the linked PR #138 if it solves your issue? Thanks!

**Comment by N-Molham** [comment]
@andrzejpiotrowski thanks for notifying me
