### ISSUE TITLE
Prolongation of expiration

### ISSUE THREAD

**Issue by Lars-** [Tmeister/wp-api-jwt-auth#139]
Hello,

I'm using the JWT plugin, but I can't find any documentation on how to prolong a token. In my case, an android app will communicate with the WP Rest API, but it would be weird if you needed to login every week.

So is there something (without changing the expiration time itself) to prolong the token?

Thanks.

**Comment by jon1wt** [comment]
Hi, you can manage the time [https://github.com/Tmeister/wp-api-jwt-auth#jwt_auth_expire](url), but I don recommend extend the time, you can update the token if is expired using some session service, not making the user login again if you have the data saved

**Comment by katerlouis** [comment]
> Hi, you can manage the time [https://github.com/Tmeister/wp-api-jwt-auth#jwt_auth_expire](url), but I don recommend extend the time, you can update the token if is expired using some session service, not making the user login again if you have the data saved

@jon1wt 

I'm new to authentication and am struggling to understand the use of refresh tokens in general– As extending expiration time is merely a workaround, I want to follow your advice, but absolutely do not understand it :D

Could you elaborate on "update the token using some session service"?

Also: Lets say I haven't used the app in a month, open it back up and call the rest endpoint "my-custom-api/v1/products" – Inside the php code handling that custom rest endpoint, I do not check for authentication at all since the plugin does that for me, nice! But now after a month the stored token is no longer valid and before my custom endpoint could "update the token" (?), the api responds with "expired token" – So where exactly would I "update the token"? 

Sorry if this is trivial to you

**Comment by jon1wt** [comment]
Hello @katerlouis 

The flow on the frontend or app side, I think, is the one you need to learn. In most frameworks, a service is created for these functions.

But the simplest way to do it, taking your example, is to do the following:

- you make the request
- if it responds that the token has expired
- you make the request for a new token
- you make the request again to the endpoint with the new token

The function of handling the tokens, as I told you before, is done in a session service or in an authentication controller on the frontend or app side.
