### ISSUE TITLE
How get ID User

### ISSUE THREAD

**Issue by cyberespia** [Tmeister/wp-api-jwt-auth#153]
`{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvbWlob3N0Lm9yZ1wvcHJ1ZWJhcyIsImlhdCI6MTU1MzcyNDM4MSwibmJmIjoxNTUzNzI0MzgxLCJleHAiOjE1NTQzMjkxODEsImRhdGEiOnsidXNlciI6eyJpZCI6IjIifX19.rgi5Q2c8RCoHRp-lJiJN8xQaOavn9T_q8cmf8v1-57o",
    "user_email": "abc@test.com",
    "user_nicename": "prueba",
    "user_display_name": "Prueba"
}`

How can I get the user ID?

**Comment by ianemv** [comment]
Have you solved your issue? For now I just added user id data at generate token function of the class-jwt-auth-public, a little bit of hacky in a way.
`
'user_id'           => $user->data->ID`

Not sure for now if it can be added to register_rest_field

**Comment by cyberespia** [comment]
Initially I had to decode (base64) the token and extract the ID. But your solution has worked for me and much faster, thank you very much.

in /plugins/jwt-authentication-for-wp-rest-api/class-jwt-auth-public.php


`        $data = array(
            'token' => $token,
            'user_email' => $user->data->user_email,
            'user_nicename' => $user->data->user_nicename,
            'user_display_name' => $user->data->display_name,
            //add this
            'user_id' => $user->data->ID,
        );`

**Comment by ianemv** [comment]
Great!

**Comment by Mulli** [comment]
While source code always works... how about the following:
`function jwt_auth_function($data, $user) {
	$data['user_role'] = $user->roles;
	return $data;
}
add_filter( 'jwt_auth_token_before_dispatch', 'jwt_auth_function', 10, 2 );`

Its for user role but you may try user id instead.

**Comment by ianemv** [comment]
@Mulli That's way better. Will apply that instead.

**Comment by cyberespia** [comment]
@Mulli Excellent!!!

**Comment by ianemv** [comment]
@cyberespia Maybe you too didn't noticed the comment. 
/** Let the user modify the data before send it back */ 
I've only seen after @Mulli answered. Been looking way to use add_filter. Thanks Mulli for the heads-up!

**Comment by nilsnolde** [comment]
@Mulli That's neat, but the hook is only available for the `/token` endpoint, not the `/token/validate` endpoint.

@Tmeister would you accept a PR to add `user_id` as a response field to both endpoints? 

Short background:

This considerably helps for headless WooCommerce shops where JWT is really only an initial authentication method, but all actual shop management (purchases, customer management etc) calls are authenticated over a WooCommerce admin account. That's due to the permissions limitations of WooCommerce customers. So, the frontend needs to know the current `user_id` to make WooCommerce calls over admin authentication on behalf of the current user. I'd like to use the `validate` endpoint for cases where customers try to access "private" pages after closing the browser and all site state is lost, so I need to access the user ID somehow in case the token is still valid. Hope that makes sense. And having those modifications available upstream would be nice:)

**Comment by fafshari** [comment]
Any update on this? It would be very helpful to have the user_id accessible with validate as @nilsnolde pointed out in that use case scenario. Also from an API standpoint, if certain API calls require an authenticated user, it only makes sense to be able to retrieve the user ID from the valid token rather than programmatically creating a new token every time you need an ID.
