### ISSUE TITLE
Only allow REST API access if the user is authenticated

### ISSUE THREAD

**Issue by corsacca** [Tmeister/wp-api-jwt-auth#53]
Is this the best way to go about disabling REST API except the jwt-auth routes and when the user is authenticated?

```
    public function rest_pre_dispatch($request)
    {
        if (is_wp_error($this->jwt_error)) {
            return $this->jwt_error;
        }
        if (!$this->determine_current_user(null) && $_SERVER['REQUEST_URI'] !== "/wp-json/jwt-auth/v1/token" && $_SERVER['REQUEST_URI'] !== "/wp-json/jwt-auth/v1/token/validate"){
            return new WP_Error( 'restx_logged_out', "API Requests are only supported for authenticated requests", array( 'status' => 401 ) );
        }
        return $request;
    }
```

Thanks!

**Comment by bstras21** [comment]
I too would like to know?

**Comment by neutronstein** [comment]
@corsacca are you able to disable api access to non authenticated users using this code?

**Comment by neutronstein** [comment]
@corsacca 
Based on your snippet, I created a simple plugin with the following code.
```php
add_filter('rest_authentication_errors', function ($result) {
    if (!empty($result)) {
        return $result;
    }

    if (!is_user_logged_in() && $_SERVER['REQUEST_URI'] !== "/wp-json/jwt-auth/v1/token" && $_SERVER['REQUEST_URI'] !== "/wp-json/jwt-auth/v1/token/validate") {
        return new WP_Error('rest_not_logged_in', 'You are not currently logged in.', array('status' => 401));
    }
    return $result;
});
```

**Comment by corsacca** [comment]
@NeutronStein Thanks. That is cleaner. It seems to work as intended.

**Comment by trdocker** [comment]
Hi - I added the filter to my constructor. But when I start a request, I get the message: You are not currently logged in. So, in my header I sent the Authorization with my Bearer TOKEN.

For example: http://dev-wp.dev/wp-json/api/comp/v1/plugins

With this request I get all installed plugins. So, how to use the JWT Plugin? BTW: I am using nginx instead of apache. I added

fastcgi_pass_header Authorization;
fastcgi_param Authorization $http_authorization; 

to my nginx.conf. But it is not possible, to restrict the api access, if the user is calling the api without sending the header informations.

Any ideas?

**Comment by corsacca** [comment]
@trdocker, does the `/wp-json/jwt-auth/v1/token` url work? (try with and without the filter)

**Comment by trdocker** [comment]
@corsacca  Yes, sure. `/wp-json/jwt-auth/v1/token` and `/wp-json/jwt-auth/v1/token/validate` works with and without the filter. But how to use the JWT with the REST2.0 plugin? I tought, that I have only access to the api if I set the header Authorization with my token...

**Comment by corsacca** [comment]
JWT just authenticates the user.
Say i have private posts and am accessing them using the rest api at `/wp-json/my-posts/v1/posts` 
If i try to access without authentication, i should get an authentication errror. 
If i sent the user's JWT token, then the rest api should respond with the private posts.

All the filter does is disable the rest api if the user is not authenticated using JWT.

edit: without the filter all your public posts will be available on the rest api whether or not the request is authenticated

**Comment by trdocker** [comment]
Hmm ok - but what I want is, to call a rest route and get only access if the authentication header is set with the correct token. Without the header or a wrong token, I want to restrict the access. The second idea was, to send the header and to add custom function, which calls the `/wp-json/jwt-auth/v1/token/validate` to validate the access. But I think, that this is not the best idea...

**Comment by corsacca** [comment]
@trdocker the `is_user_logged_in()` in the filter checks to see if the user is authenticated. 
It might be that the filter is not being called for you. Try placing it outside your class.
edit: the one by NeutronStein

**Comment by trdocker** [comment]
(facepalm) - Perfect man! Thanks!!! That fixed my "mistake alias problem" ;)

Cheers

**Comment by ricardobrg** [comment]
@NeutronStein I was using your code but had some trouble with a REST Client that append querystring parameters (don't know why, maybe caching...). So I've modified it a little bit:

    add_filter( 'rest_pre_dispatch', function() {
	 $url = strtok($_SERVER["REQUEST_URI"],'?');
	 if ( !is_user_logged_in() &&  
		  !in_array($url, array (
			"/wp-json/jwt-auth/v1/token" , 
			"/wp-json/jwt-auth/v1/token/validate",
			))){		 
	  return new WP_Error( 'not-logged-in', 'API Requests to '.$url.' are only supported for authenticated requests', array( 'status' => 401 ) );
    }
    } );

**Comment by McFlemchSoda** [comment]
Hi,
Where is this code snippet supposed to be placed to make it work? I also need all api calls to be authenticated. Thanks.

**Comment by ricardobrg** [comment]
@McFlemchSoda it can be placed in your theme's functions.php or as a plugin.

**Comment by bfintal** [comment]
@ricardobrg Thanks for the code, it works great!

**Comment by shanebp** [comment]
@ricardobrg 
Yes, thanks for the code, it works great!

**Comment by gtso86** [comment]
I had some problems using @ricardobrg function because CORS preflight:
![image](https://user-images.githubusercontent.com/319048/42694563-3ee59506-8689-11e8-8b8a-a6d161a85d2a.png)

I've found this way to "fix" this was adding this code too:

```
if ($_SERVER['REQUEST_METHOD'] == 'OPTIONS') {
    header('Access-Control-Allow-Origin : *');
    header('Access-Control-Allow-Methods : POST, GET, OPTIONS, PUT, DELETE');
    header('Access-Control-Allow-Headers : *');
    exit;
}
```
![image](https://user-images.githubusercontent.com/319048/42694589-56ff3a5c-8689-11e8-8450-78470aab9142.png)

That way, when browser try to connect with the endpoint first attempt works normally

**Comment by kamane** [comment]
I tried to handle authorization for WP user rest API but have faced this problem : postman GET user request worked but request from  ionic ( angular ) , trigger a  CORS call  : OPTION request , witch is blocked  ,   . so i changed this filter :

 (rest_pre_dispatch or rest_authentication_errors)  to this   :  : +1:  rest_request_before_callbacks

my  final filter is  : 

add_filter( 'rest_request_before_callbacks', function() {
 $url = strtok($_SERVER["REQUEST_URI"],'?');
 if ( !is_user_logged_in() &&  
	  !in_array($url, array (
		"/wp-json/jwt-auth/v1/token" , 
		"/wp-json/jwt-auth/v1/token/validate",
		))){		 
  return new WP_Error( 'not-logged-in', 'API Requests to '.$url.' are only supported for authenticated requests', array( 'status' => 401 ) );
} 
} );

**Comment by rocifier** [comment]
Hi, I have tried the above code + sending an Authorization header with the Bearer token to my wp-json custom endpoint. However the check in the filter for is_user_logged_in() always returns false. Any idea why that might be? I have verified in the endpoint by dumping getallheaders() that the Authorization header is present and correct.

EDIT: Turns out the default wordpress .htaccess doesn't pass through the Authorization header. After ammending .htaccess my problem is solved.
