### ISSUE TITLE
Get “jwt_auth_bad_iss” with WPML

### ISSUE THREAD

**Issue by pesseba** [Tmeister/wp-api-jwt-auth#68]
If I’m using WPML plugin for content localization I got this error if I got the token in a different url from language.

So, if I got the token with: “https://site.com/wp-json/jwt-auth/v1/token/”
I can’t retrieve content from “https://site.com/pt-br/wp-json/jwt-auth/v1/token/”
or from “https://site.com/wp-json/jwt-auth/v1/token/?lang=pt-br”

It’s return “jwt_auth_bad_iss”

There is a way to avoid this problem?

**Comment by pesseba** [comment]
I solved this in wpml forum:
http://wpml.org/forums/topic/retrieve-all-languages-entries-of-a-post_type-by-wp-rest-api/

The solution was a plugin to manage some kind of requests

**Comment by abdallahnofal** [comment]
Hello, I just edited this file `public/class-jwt-auth-public.php` and changed `get_bloginfo('url')` to `site_url()` 

What happens is when you generate token with `https://site.com/`  and try to validate it on `https://site.com/pt-br` you'll get this error, because `get_bloginfo('url')` returns the domain with the current language so when you change it to `site_url()` it will always use `https://site.com/` for ISS validation with any language.

**Comment by mineralwassermedium** [comment]
instead of editing the file `class-jwt-auth-public.php` directly, it would probably be better to use this filter: `apply_filters('jwt_auth_token_before_sign', $token, $user)` something like this:

`add_filter('jwt_auth_token_before_sign', function($token, $user) { $token['iss'] = site_url(); return $token;}, 10, 2);`

**Comment by Vextil** [comment]
@mineralwassermedium That won't work, as the problem arises in this line:
```
 if ($token->iss != get_bloginfo('url')) {
```
Even if you replace the ISS stored in the token, ```get_bloginfo('url')``` still returns the URL with the language at the end which can cause a mismatch.

**Comment by MakiOmar** [comment]
I could manage to fix this by hooking into `home_url` and return `site_url` instead if the request is JSON:
```
// Fix JWT bad iss
add_filter( 'home_url', function($uri){
    if (! strpos( $_SERVER['REQUEST_URI'], 'wp-json')){
      return $uri;  
    }
    return site_url();
    
    
});
```

**Comment by ruuska** [comment]
After hooking into `home_url` and returning `site_url` requesting the `token/validate?lang=en` route works but requesting any other translated route still errors with `jwt_auth_bad_iss` .

Any ideas on why this would be the case?
I'm assuming that `validate_token` runs earlier when the route is not `token/validate` and for some reason my `home_url` hook is not yet registered when `determine_current_user` runs but I don't know why that would be the case if I register my hook in my templates functions.php file.
