### ISSUE TITLE
It's not checking authentication.

### ISSUE THREAD

**Issue by SmartWeb25** [Tmeister/wp-api-jwt-auth#82]
I'm using wordpress 4.8.1 and after activating the plugin, I can call other APIs without authentication header. 
Is there anything to configure for it beside the secret-key in wp-config.php?

**Comment by marcin-solvenet** [comment]
I have similar issue. I tried Disable REST API plugin  https://wordpress.org/plugins/disable-json-api/
but it is checking for cookie presence not jwt token.
Based on below discussion
https://stackoverflow.com/questions/43972001/authenticate-wp-rest-api-get-requests

I guess we need to add filter and instead of calling  "! is_user_logged_in()" will be checking jwt token.
Can you please give advise to fix this isssue?
Thanks

**Comment by rocifier** [comment]
Same issue here, wordpress 5.0.3. Is anyone actually using this plugin in production?

**Comment by acerioni** [comment]
I have the same issue as well :-(
