### ISSUE TITLE
Custom Endpoint

### ISSUE THREAD

**Issue by sevekim** [Tmeister/wp-api-jwt-auth#97]
In angular, I have following to get the JWT token for wordpress.

    import { HttpClient, HttpHeaders} from '@angular/common/http';
    ...
    logIn(){
        let loginInfo ={
            username: 'admin',
            password: 'password.'
        };   

        let headers = new HttpHeaders();
        headers.set('Content-Type', 'application/json');
              
        this.http.post( this.apiURL + 'wp-json/jwt-auth/v1/token',loginInfo,{headers: headers}).subscribe(data => {    

            this.token = data['token'];                   

         },err => {          
           console.log(err);

         })
    };

Here, I get a successful `token` for the logged in user.

To access a custom endpoint, I am sending the token as following:

     Test() {

        let test = this.apiURL + 'wp-json/test/v1/test';

        let headers = new HttpHeaders({
            'Content-Type': 'application/json',
            'Authorization': 'Bearer ' + this.token
        });

        this.http.get(test,{headers: headers}).subscribe(data => {
            console.log(data);
          
	    }, error=>{
            console.log(error);
            
        });
    };

**In the php:**

     add_action( 'rest_api_init', function ($data) {
			register_rest_route( 'test/v1', '/test/', array(
					'methods' => 'GET',
					'callback' => 'testFunction',
					'permission_callback' => function () {
						return current_user_can( 'edit_others_posts' );
					}
			) );
	} );
	
		function testFunction($data) {
			
			$current_user = wp_get_current_user();
			
			return $user_id;
		};

However I am still get `forbidden` error:

    {code: "rest_forbidden", message: "Sorry, you are not allowed to do that.",}

My understanding is that using `permission_callback` I can check the user authentication. 

Ultimately, I am trying to get the `loggedin` user id. 

What am I missing?

Any help will be much appreciated.

**Comment by alaa-alsalehi** [comment]
it suppose all is OK I think if the user can edit other posts then all must work just fine

**Comment by palaa159** [comment]
Mine too. Still seeking answers...

**Comment by MaxicanArmy** [comment]
@sevekim I am having this issue as well. I can validate permissions using permission_callback, but when trying to save data in my callback I need the validated user's ID and I can't access it. Did you find a way to access wp_get_current_user() in the callback?

**Comment by caraffa** [comment]
Hi, I'm facing very similar problems.
I'm trying to implement a basic login structure with Angular5/Wordpress/RestAPI/JWT-token, without much luck.
After many sleepless nights I've come to suppose that there is a big misunderstanding about what the plugin claims to do and what it actually does.
This JWT plugin is very good but there is huge confusion about the concept of _Authentication_ vs _Authorization_! 
What this plugin does (very well) is Authorization, **not** Authentication!
Once properly set up, with all the headers set with the proper scheme (authorization: Bearer &lt;token&gt;), this plugin will effectively prevent unauthorized access to specified resources, _but_...
There is a big "_but_"!
In order to performe certain operations, Wordpress needs a _**logged in**_ user!
In Wordpress' REST API, users are **not** considered logged in (i.e. _authenticated_) by default.
If you browse through wordpress' code/documentation, you will discover that, in order to perform certain operations, Wordpress checks for a valid nonce! And valid nonces can be generated only after a user has signed on _through wordpress' login page_!
Lacking a nonce, most REST API actions involving data _creation_ (new posts, user, and the like) will fail!
So it is somehow misleading to state that this plugin can _replace_ wordpress' authentication.
Real authentication means generating proper session cookies, along with relevant nonces, and this plugin doesn't do that or doesn't override that (Unless the developer knows a way which we don't know)

**Comment by caraffa** [comment]
@sevekim and @MaxicanArmy 
There is an error in Sevekim testFunction(). $user_id is undefined, you should use something like 

`return $current_user->ID;`

But that's not the point even. If you dump to the log the value of $current_user, you'll discover that it is always NULL. Precisely because REST API sets it to NULL, whenever a valid nonce is missing.
I managed to move somehow a bit further, using the 'jwt_auth_token_before_dispatch' filter, like this:
```
add_action('rest_api_init', function () {
    add_filter('jwt_auth_token_before_dispatch', function ($data, $user) {
        // Tells wordpress the user is authenticated
        wp_set_current_user($user->ID);
        $data['nonce'] = wp_create_nonce('wp_rest');
        return $data;
    }, 10, 2);
});

```
As you see I try to generate a nonce and add it to the response body, along with the token, but this doesn't solve the problem because that nonce is afterwards checked agains a session ID that does not exist (no user is logged in)!
I think this is the real problem!

**Comment by MaxicanArmy** [comment]
@sevekim 

@caraffa is correct about you returning $user_id without ever setting it. What happens for you, sevekim, when you change your testFunction return value to "return $current_user;"?

**Comment by rocifier** [comment]
I tested this example, modifying the line mentioned above to "return $current_user;" and I get a default object with ID set to 0. The object indicates there is not a user logged in. This is a real bummer, I was hoping the plugin would always set up a current user whenever I am in a REST api endpoint...
